dist: bionic
addons:
  apt:
    packages:
      - genisoimage
      - gnupg2
      - qemu-utils
      - qemu-kvm
      - rpm
      - systemd-container
matrix:
  include:
    - name: fedora-30
      arch: amd64
      language: python
      python: 3.7
      script:
        # ubuntu's rpm package sets dbpath to ~/.rpmdb, which makes rpm fail...
        - sudo sh -c 'mkdir /etc/rpm; echo "%_dbpath /var/lib/rpm" > /etc/rpm/macros'
        - sudo env "PATH=$PATH" "PYTHONUNBUFFERED=1" test/run --arches x86_64 --distro fedora-30
    - name: fedora-30
      arch: arm64
      language: python
      python: 3.7
      script:
        # ubuntu's rpm package sets dbpath to ~/.rpmdb, which makes rpm fail...
        - sudo sh -c 'mkdir /etc/rpm; echo "%_dbpath /var/lib/rpm" > /etc/rpm/macros'
        - sudo env "PATH=$PATH" "PYTHONUNBUFFERED=1" test/run --arches aarch64 --distro fedora-30
    - name: fedora-31
      arch: amd64
      language: python
      python: 3.7
      script:
        # ubuntu's rpm package sets dbpath to ~/.rpmdb, which makes rpm fail...
        - sudo sh -c 'mkdir /etc/rpm; echo "%_dbpath /var/lib/rpm" > /etc/rpm/macros'
        - sudo env "PATH=$PATH" "PYTHONUNBUFFERED=1" test/run --arches x86_64 --distro fedora-31
    - name: fedora-31
      arch: arm64
      language: python
      python: 3.7
      script:
        # ubuntu's rpm package sets dbpath to ~/.rpmdb, which makes rpm fail...
        - sudo sh -c 'mkdir /etc/rpm; echo "%_dbpath /var/lib/rpm" > /etc/rpm/macros'
        - sudo env "PATH=$PATH" "PYTHONUNBUFFERED=1" test/run --arches aarch64 --distro fedora-31
    - name: fedora-32
      arch: amd64
      language: python
      python: 3.7
      script:
        # ubuntu's rpm package sets dbpath to ~/.rpmdb, which makes rpm fail...
        - sudo sh -c 'mkdir /etc/rpm; echo "%_dbpath /var/lib/rpm" > /etc/rpm/macros'
        - sudo env "PATH=$PATH" "PYTHONUNBUFFERED=1" test/run --arches x86_64 --distro fedora-32
    - name: fedora-32
      arch: arm64
      language: python
      python: 3.7
      script:
        # ubuntu's rpm package sets dbpath to ~/.rpmdb, which makes rpm fail...
        - sudo sh -c 'mkdir /etc/rpm; echo "%_dbpath /var/lib/rpm" > /etc/rpm/macros'
        - sudo env "PATH=$PATH" "PYTHONUNBUFFERED=1" test/run --arches aarch64 --distro fedora-32
